# Generated by Django 4.1 on 2022-10-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='n/a', max_length=254),
            preserve_default=False,
        ),
    ]
