dev:
	python manage.py runserver --settings=config.settings.dev

kevin-dev:
	python manage.py runserver --settings=config.settings.dev_kevin

prod:
	python manage.py runserver --settings=config.settings.prod

dev-shell:
	python manage.py shell --settings=config.settings.dev

prod-shell:
	python manage.py shell --settings=config.settings.prod

dev-install:
	pip install -r requirements/dev.txt

prod-install:
	pip install -r requirements/prod.txt

